### ISSUE TITLE
Image Link Broken in "Install from Web"

### ISSUE THREAD

**Issue by Darko23** [joomla-extensions/install-from-web-client#12]
Hello.

I use joomal 3.3.6 (German) and see that Images in the "install from Web"-Section are broken.
![error](https://cloud.githubusercontent.com/assets/10371123/5595493/895b854e-9274-11e4-9b72-c0d9be4fc401.png)

can somebody look at this and fix the Problem?

Thank you .

best Regards and hapy new year

Darko Grgic

www.velcon.de
www.realisticarma.com

**Comment by zero-24** [comment]
Also reported here: https://github.com/joomla/joomla-cms/issues/5620

**Comment by PhilETaylor** [comment]
Duplicate of #10

**Comment by Bakual** [comment]
Closing as duplicate
