### ISSUE TITLE
Language strings issues

### ISSUE THREAD

**Issue by infograf768** [joomla-extensions/install-from-web-client#13]
Missing string in core:
COM_INSTALLER_WEBINSTALLER_INSTALL_RETRY

Also
COM_INSTALLER_WEBINSTALLER_INSTALL_WEB_LOADING_ERROR="Cannot connect to the Joomla! server. Please try again later."
has no variable and is used in a sprintf
```
<a class="close" data-dismiss="alert">×</a><?php echo JText::sprintf('COM_INSTALLER_WEBINSTALLER_INSTALL_WEB_LOADING_ERROR', $retry); ?>

```

**Comment by beat** [comment]
This is not core Joomla. As you know, the strings are in core Joomla to make it easy for translators and users with language files for official plugins.

Anyone: Please do a PR towards core joomla for the missing string.

The second one is neither a bug nor a missing feature. The sprintf was there for some other languages as I understand. As you are our expert in languages and semantics, if you believe that the sprintf is not needed, simply do a PR to remove it :)

Sorry for not replying earlier. I want to give a chance to the community to work on easy and non-urgent tasks :) .
