### ISSUE TITLE
Doesn't work with SSL

### ISSUE THREAD

**Issue by nicksavov** [joomla-extensions/install-from-web-client#2]
Hi guys,

Install From Web doesn't work with SSL in the admin area. It spins for a long time, then won't display. Instead it states "Cannot connect to the Joomla! server. Please try again later."

In Chrome, it has this warning:
https://support.google.com/chrome/answer/1342714?hl=en

The issue might be due to the following code:
apps_base_url = 'http://appscdn.joomla.org/webapps/';

**Comment by IotaSpencer** [comment]
So is it fixed now?? lol

**Comment by 810** [comment]
@beat could you update the version number and do a release. Now it isn't working.

**Comment by beat** [comment]
This issue has been fixed for Joomla 3.4 version of Install from web. Today it will be also available for earlier versions same time as for 3.6 (staging), thus I'm now closing this issue.
