### ISSUE TITLE
For Next Release

### ISSUE THREAD

**Issue by nicksavov** [joomla-extensions/install-from-web-client#21]
1) SSL fix is already committed. https://github.com/joomla-extensions/install-from-web-client/issues/2 can be closed once a package is created and a message is left in https://github.com/joomla-extensions/install-from-web-client/issues/2 to test.

2) https://github.com/joomla-extensions/install-from-web-client/issues/8 is done. It can be closed.

3) https://github.com/joomla-extensions/install-from-web-client/issues/10 is done in the serverside. It can be closed.

4) Merge https://github.com/joomla-extensions/install-from-web-client/pull/6

5) ~~Merge https://github.com/joomla-extensions/install-from-web-client/pull/7~~ - Check https://github.com/joomla-extensions/install-from-web-client/pull/23 instead

6) Merge https://github.com/joomla-extensions/install-from-web-client/pull/15

7) ~~Merge https://github.com/joomla-extensions/install-from-web-client/pull/20~~ - Merged

8) ~~Remove 2.5 support: https://github.com/joomla-extensions/install-from-web-client/pull/18~~ - Merged

9) Create a test package.

**Comment by beat** [comment]
1) ok - already done
2) closed #8 
3) closed #10 
4) #6 is imho already fixed Joomla-core-side (and proposed fix may create issues in 3p plugins)
5) #23 is buggy according to your tests
6) #15 got closed by the proposer (small comments improvements, nothing critical anyway)

**Comment by 810** [comment]
Any update please...

**Comment by beat** [comment]
Sorry will do a build and make available online for 3.5 in next days.

**Comment by 810** [comment]
Ok thnx

**Comment by beat** [comment]
All issues listed in here are addressed and closed, so closing this meta-issue too.
