### ISSUE TITLE
Popular Extensions - home page

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/install-from-web-client#34]
This is NOT popular extensions it is ALL extensions sorted by score (unless a different sort has been chosen) - there are 972 pages

I would suggest either renaming this to "ALL" or limiting the number of extensions fetched to be a true popular list.

Right now a user could select popular an then change the sort by reviews and think they are seeing something that they are not

**Comment by brianteeman** [comment]
Also if you have selected an extension from this default page it will display the string "Popular extensions listed on the Joomla Extension Directory" as the category which is clearly not correct if the previous page was sorted by reviews and it had zero reviews

**Comment by rdeutz** [comment]
I did filter on popular, so might be an issue with the JED not filtering correct, will look into it

**Comment by brianteeman** [comment]
It is sorting by popular - its just including every extension - so it is really All - sorted by popular

**Comment by rdeutz** [comment]
look here https://github.com/joomla-extensions/install-from-web-client/blob/development/plugins/installer/webinstaller/webinstaller.php#L145 it not sorting it is a property of an extension, must say I just copied this with really checking if that works

**Comment by rdeutz** [comment]
it's strange, we have 7261 Extensions in the JED, when I go to Top Rated and then to end in the pagination I am on page 414, 414*18+18 = 7452. so we have more Top Rated Extensions as we have in total. And if you select the last extension on this page it has the popular tag. 
So all and more is popular :-)

**Comment by brianteeman** [comment]
Closing after 8 months as clearly the "new" install from web plugin has abandoned

**Comment by rdeutz** [comment]
that's not true, the api is atm unusable so no chance to use the new version now
