### ISSUE TITLE
Hathor

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/install-from-web-client#37]
Everything is broken in Hathor
http://i.tee.mn/FhVa.png

**Comment by rdeutz** [comment]
I know, as I mentioned in the release notes there are NO overwrites for Hathor. That's step 2

**Comment by brianteeman** [comment]
Ah ok - I just spotted code for hathor so tried - should have read more clearly

**Comment by brianteeman** [comment]
What release notes?

**Comment by Bakual** [comment]
https://github.com/joomla-extensions/install-from-web-client/releases

**Comment by brianteeman** [comment]
Thanks

**Comment by brianteeman** [comment]
Closing after 8 months as clearly the "new" install from web plugin has abandoned
