### ISSUE TITLE
Remove the "First/Last" parameter

### ISSUE THREAD

**Issue by Bakual** [joomla-extensions/install-from-web-client#46]
With J3.6 the installer is built with a plugin for each tab, similar to the install from web plugin.
The position of each tab is determined by the ordering of the plugins.

This makes the position parameter in the ifw plugin obsolete and actually limits the functionality.
Thus that parameter should be removed.

**Comment by beat** [comment]
A PR that works for both older releases and 3.6+ (detecting version) is welcome to implement this.

**Comment by Bakual** [comment]
Do we really need to make it work in older versions as well?
When 3.6.0 is released, the 3.5.0 and older versions of the CMS aren't supported anymore by the project.
We could leave the old plugin version there for the old CMS versions and the new version will only be proposed for 3.6.0 and higher.
The plugin for 3.5.x and older is just no longer supported. If it breaks for whatever reason, the fix is to update to 3.6.0 and use the new plugin version there.

**Comment by Bakual** [comment]
Checking https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml we actually already do that currently. Version 1.0.5 is for Joomla 3.2 - 3.4 and for 3.5 version 1.1.0 is used.

**Comment by zero-24** [comment]
Mind reading @bakual :)

**Comment by mbabker** [comment]
Gone in 2.0.
