### ISSUE TITLE
Add "Install from Web" option not enabling

### ISSUE THREAD

**Issue by nikitadhiman** [joomla-extensions/install-from-web-client#49]
Expected result

An install from web options in tab at extension install page
Actual result

Refer the screen shot
Additional comments

I tried doing this many times, still the same result
![web](https://cloud.githubusercontent.com/assets/8037750/19756748/7134b64c-9c3c-11e6-8e9c-7c06fb6f7931.png)

**Comment by coolbung** [comment]
Seems to be working for me.

I think your server is blocking outbound network connections, so you're facing this issue. Try speaking to your hosting provider, they should be able to help.

**Comment by coolbung** [comment]
Seems to be working for me.

I think your server is blocking outbound network connections, so you're
facing this issue. Try speaking to your hosting provider, they should be
able to help.

**Comment by HLeithner** [comment]
This seems to be an server issue and hopefully fixed after 6 years, I'm closing this.
