### ISSUE TITLE
3.7.0b1 - No extensions listed!!! 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-extensions/install-from-web-client#51]
<img width="1439" alt="screen shot 2017-02-02 at 21 26 29" src="https://cloud.githubusercontent.com/assets/400092/22569134/48eb492c-e98e-11e6-9891-5b4951bf626a.png">

**Comment by Bakual** [comment]
Works for me on current staging (3.7.0-rc1). @PhilETaylor Can you check if that is still an issue for you?

**Comment by PhilETaylor** [comment]
I still have this bug https://github.com/joomla-extensions/install-from-web-client/issues/50#issuecomment-282851002 but at least now I can see extension if I overcome that #50 bug by clickign another tab and then back to the "Install from web" tab
