### ISSUE TITLE
Loading .... issue [after installing an extension]

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-extensions/install-from-web-client#53]
This is still a problem, majority of loading issues are fixed with the last release/pr #35 but there remains an issue when Install From Web is the first tab, and immediately after installing an extension, thepage loads with the success text for that, but the Install from web tab pane is blank (although the code triggers the load)

**Comment by Darth-Carrotpie** [comment]
Similar bug for me. It appears as if the content was loaded, but the screen remains inactive with a loading sign on top of it. 
![joomla bug](https://cloud.githubusercontent.com/assets/9535319/25998190/76da3c48-3728-11e7-9568-a695d47c4788.PNG)

**Comment by PhilETaylor** [comment]
Ive not seen that bug

**Comment by ZerooCool** [comment]
I have the same.
chown www-data:www-data ans chmod 777 don't change that.
how i can search the good way ?

I have Joomla 3.8.1, worked with the first installation.
Now, with my local test this option is broken.

When i install a new extension, the extension use daemon group ( not www-data ).

**Comment by webmaster-cepr** [comment]
I'm running into the same/similar issue. Testing the plugin update and I now get the following on the Install From Web tab: 

![image](https://user-images.githubusercontent.com/5262244/55577225-14511800-56e1-11e9-8f95-35adf28d3ddc.png)
