### ISSUE TITLE
Prepare for Downloads Site Support

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/install-from-web-client#54]
In the next few days we will turn on the Extensions section of the downloads site which will include Weblinks and Install from Web. To support this, the [update server definition](https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml) should be ready to use the site when we enable the new section.  This will require the following updates:

http://appsserver.joomla.org/webapps/jedapps/downloads/plugin/plg_webinstaller_3.2v1.0.5.zip will be served via https://downloads.joomla.org/extensions/install-from-web/1-0-5/plg_webinstaller_3.2v1.0.5.zip

http://appsserver.joomla.org/webapps/jedapps/downloads/plugin/plg_webinstaller_3.7v1.1.1.zip will be served via https://downloads.joomla.org/extensions/install-from-web/1-1-1/plg_webinstaller_3.7v1.1.1.zip

@beat I will ping again when we launch the section, if you could please be ready to update the XML file that'd be greatly appreciated.

**Comment by beat** [comment]
@mbabker Awesome news! Thanks! Please also provide (privately, you have my contacts) the way to upload new versions for new releases.

**Comment by mbabker** [comment]
@beat I've turned on the new area on the site, you can make this change now.  I will ping you offline with credentials to log into the site.
