### ISSUE TITLE
Can't Connect to the Joomla! Server

### ISSUE THREAD

**Issue by webmaster-cepr** [joomla-extensions/install-from-web-client#57]
Testing the 2.0.0 upgrade and I get the following on the Install from Web tab:

![image](https://user-images.githubusercontent.com/5262244/55577393-8164ad80-56e1-11e9-9c67-230db9184c8c.png)

**Comment by mbabker** [comment]
With your browser's developer tools open, try loading the install from web tab and see if there are any errors in the console.  If not, check the network tab for requests to `https://appscdn.joomla.org` and see what those requests are returning.

**Comment by mbabker** [comment]
Looks to be related to #56 so closing for now.  If it turns out this is a completely separate issue, this can be re-opened.
