### ISSUE TITLE
Option Last Tab Request

### ISSUE THREAD

**Issue by AlexanderSk** [joomla-extensions/install-from-web-client#58]
Hello, Install from web had in previous versions an option to place it as last item and currently it is not available. Is it possible to bring in back to the scene please?

The reason is that once we are on the install menu the web tab takes some time to load and is actually annoying while of course it is a really good to have as an option but not something that is used everyday.

Kind Regards.

**Comment by mbabker** [comment]
Hi, this was a deliberate change to make the Install from Web plugin behave the same as the rest of the installer plugins.  As of Joomla! 3.6, all the install methods (upload, URL, folder) were moved to plugins and can have their ordering customized and each method enabled/disabled.  With the plugin's 2.0 release, you can customize its position on the install page by reordering the "installer" group plugins the way you want them.

**Comment by AlexanderSk** [comment]
Yes indeed, really nice info, thank yoy very much!
