### ISSUE TITLE
Can not upgrade Installer - Install from Web 1.1.1 to 2.0.1 on Joomla 3.9.5.

### ISSUE THREAD

**Issue by dedetok** [joomla-extensions/install-from-web-client#59]
I can not upgrade "Installer - Install from Web" from 1.1.1 to 2.0.1, not from direct online update nor from uploaded zip file.

Here is my environment:

- PHP 7.2.17.
- Joomla 3.9.5.

here is error message
Warning
```
Copy failed: /home/[user]/public_html/web/joomla/tmp/install_5cb3ee1cc3a65/webinstaller.php to /home/[user]/public_html/web/joomla/plugins/installer/webinstaller/webinstaller.php
JInstaller: :Install: Failed to copy file /home/[user]/public_html/web/joomla/tmp/install_5cb3ee1cc3a65/webinstaller.php to /home/[user]/public_html/web/joomla/plugins/installer/webinstaller/webinstaller.php
Plugin Update: Could not copy files from the source.
Before updating ensure that the update is compatible with your Joomla! installation. 
You are strongly advised to make a backup of your installation before you start updating.
```
My root Joomla is /home/[user]/public_html/web/joomla/.

I set all permission folder and file to writable, but it does not solved the problem.

**Comment by coolbung** [comment]
Where are you picking up the package from ? v2.0.1 does not have an installable package in the release section. You will need to clone the repo, checkout tag 2.0.1 and manually create the package using the script  inside the build folder. 

https://github.com/joomla-extensions/install-from-web-client/blob/2.0.1/build/create-package.sh

**Comment by mbabker** [comment]
The packages are on https://downloads.joomla.org, they are not published with the release tags on this repo.

**Comment by dedetok** [comment]
here are list from update site:

- https://update.joomla.org/language/translationlist_3.xml
- https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
- https://update.joomla.org/core/list.xml
- https://update.joomla.org/core/extensions/com_joomlaupdate.xml

Do I need to update my update site?

**Comment by dedetok** [comment]
here are list from update site:

- https://update.joomla.org/language/translationlist_3.xml
- https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
- https://update.joomla.org/core/list.xml
- https://update.joomla.org/core/extensions/com_joomlaupdate.xml

Do I need to update my update site?

I manually download "Install from Web 2.0.1" from https://downloads.joomla.org/extensions/install-from-web
when I update using file upload, it failed.

**Comment by collierscott** [comment]
I had to rename the _plugins/installer/webinstaller_ directory before installing the plugin from [https://downloads.joomla.org/extensions/install-from-web/2-0-1](https://downloads.joomla.org/extensions/install-from-web/2-0-1) to get it to work.

**Comment by mlrmelo** [comment]
Sorry...
I can't update it, too...
I tried download the .zip file and upload one, too, but without success...
This is the message:

> **Joomla\Filesystem\File::delete: Failed deleting inaccessible file client.css**

But the file exists and the permissions are 0777 (file and directory)

**Comment by vientito** [comment]
Same error message trying to updaate either through webinstalling or downloading package. Updating always gives message about failing to delete client.css though it is permissible for system to acess and writable. I am on joomla 3.9.10 now and php version 7.1.21. This has persisted since joomla 3.9.3 up to now still not able to upgrade with same message in my system!

**Comment by HLeithner** [comment]
I hope this problem worked out at some point. Since Joomla! 3 is going into security mode only we will archive this repo. For Joomla 4+ this plugin is part of the main repository.
