### ISSUE TITLE
 Notice: Trying to access array offset on value of type null - when re-installing client

### ISSUE THREAD

**Issue by toivo** [joomla-extensions/install-from-web-client#62]
Joomla 3.9.19 on Wampserver 3.2.2: Apache 2.4.43a - MySQL 8.0.20 - PHP 7.4.7

Click the button 'Add "Install from Web" tab'.
Download client from https://downloads.joomla.org/us/extensions/install-from-web/2-0-1 and install it.

Result: 
Notice: Trying to access array offset on value of type null in C:\www\joomla39\libraries\src\Installer\InstallerScript.php on line 144

Trace:
#	Time	Memory	Function	Location
1	0.0003	368912	{main}( )	...\index.php:0
2	0.0866	1147920	Joomla\CMS\Application\AdministratorApplication->execute( )	...\index.php:51
3	0.0866	1147920	Joomla\CMS\Application\AdministratorApplication->doExecute( )	...\CMSApplication.php:196
4	0.1129	1747368	Joomla\CMS\Application\AdministratorApplication->dispatch( )	...\AdministratorApplication.php:159
5	0.1187	1771112	Joomla\CMS\Component\ComponentHelper::renderComponent( )	...\AdministratorApplication.php:101
6	0.1197	1898144	Joomla\CMS\Component\ComponentHelper::executeComponent( )	...\ComponentHelper.php:377
7	0.1198	1915072	require_once( 'C:\www\joomla39\administrator\components\com_installer\installer.php' )	...\ComponentHelper.php:402
8	0.1300	2000464	InstallerControllerInstall->execute( )	...\installer.php:19
9	0.1300	2000464	InstallerControllerInstall->install( )	...\BaseController.php:710
10	0.1325	2010576	InstallerModelInstall->install( )	...\install.php:35
11	0.3148	2065240	Joomla\CMS\Installer\Installer->install( )	...\install.php:187
12	0.3288	2192808	Joomla\CMS\Installer\Adapter\PluginAdapter->install( )	...\Installer.php:521
13	0.3320	2226144	Joomla\CMS\Installer\Adapter\PluginAdapter->triggerManifestScript( )	...\InstallerAdapter.php:712
14	0.3320	2242656	plginstallerwebinstallerInstallerScript->preflight( )	...\InstallerAdapter.php:1026
15	0.3320	2242656	plginstallerwebinstallerInstallerScript->preflight( )	...\webinstaller.script.php:140

**Comment by mbabker** [comment]
This error is coming from core, specifically [here](https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Installer/InstallerScript.php#L143-L144).  Please report to the CMS repo.
