### ISSUE TITLE
Get data from the new jed

### ISSUE THREAD

**Issue by 810** [joomla-extensions/install-from-web-client#8]
The Jed has changed to new environment, now its lost images on the webinstaller.

**Comment by coolbung** [comment]
I've been able to get most of it working, a few things remain in case anyone wants to take a shot. I won't be able to get to the remaining bits until mid next week

Here's the PR that has the work done so far. What's remaining
- Fix the category/subcategory list in sidebar
- Update the view/model for the extensions by category view

joomla-extensions/install-from-web-server#4

**Comment by beat** [comment]
Done serverside, closing.
